### ISSUE TITLE
auto update ScienceBeam commit

### ISSUE THREAD

**Issue by de-code** [elifesciences/sciencebeam-texture#19]

**Comment by giorgiosironi** [comment]
Value to update: https://github.com/elifesciences/sciencebeam-texture/blob/develop/.env#L4

Proposal:
- add new pipeline that updates using an input value (`dependencies-sciencebeam-texture-update-sciencebeam`)
- pipeline will ~~open a new PR with the change~~ change the value and commit automatically
- add trigger at https://github.com/elifesciences/sciencebeam/blob/develop/Jenkinsfile#L21 that passes the new commit value to it after the new image has been pushed

**Comment by de-code** [comment]
I believe that is now implemented (it did automatically update to `0.0.1`).
