### ISSUE TITLE
add health checks

### ISSUE THREAD

**Issue by de-code** [elifesciences/sciencebeam-texture#25]
Add health checks, in particular the GROBID container. So that it will automatically be restarted.

**Comment by giorgiosironi** [comment]
- `docker-compose` should use `restart: always`
- `healthcheck` can be defined in `docker-compose.yml` (assuming we use someone else's image, otherwise as `HEALTHCHECK` in the Dockerfile), not sure which command to run?

**Comment by de-code** [comment]
This is what I added for another project (monitor port 8070):
https://github.com/elifesciences/sciencebeam-orchester/blob/develop/docker-compose.yml#L27-L34

(I could submit a PR to get the HEALTHCHECK into the GROBID project in the future)

**Comment by giorgiosironi** [comment]
Is the `while` loop necessary? All that logic should be dealt with by Docker itself?

**Comment by de-code** [comment]
That's a good point. I didn't give it too much thought as for the other project I only used it to wait until the container is ready and just hacked something together with the help from the "internet". But thinking about it, I don't see why it should be necessary either.

As for the port check itself there seem to be many variations depending on the tools available within the container. Bash seems to be a common one available. I don't really mind at all what we use for that.

**Comment by giorgiosironi** [comment]
> depending on the tools available within the container

`bash` is definitely more common than `netcat`

**Comment by de-code** [comment]
May need to increase the priority to get this done before this Wednesday (25 July).

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/test/job/test-sciencebeam-texture/62/ has made `sciencebeam-texture--demo` healthy now:
```
CONTAINER ID        IMAGE                                                                        COMMAND                  CREATED             STATUS                   PORTS                    NAMES
935e03eb284a        elifesciences/sciencebeam_texture:9748c4105544ab6db259faa6073de1e67ae2f9ce   "npm run start:prod"     3 minutes ago       Up 3 minutes (healthy)   0.0.0.0:4000->4000/tcp   sciencebeam-texture_texture_1
88300c4042ed        elifesciences/sciencebeam:035530236b9c7e514f787cce06bb0344703a365a           "./server.sh ' --hos…"   3 minutes ago       Up 3 minutes             0.0.0.0:8075->8075/tcp   sciencebeam-texture_sciencebeam_1
c2865a4b55de        lfoppiano/grobid:0.5.1                                                       "/tini -- ./grobid-s…"   3 minutes ago       Up 3 minutes (healthy)                            sciencebeam-texture_grobid_1
```
It has only 1.9 GB free so an additional volume would help.

**Comment by de-code** [comment]
@giorgiosironi okay, could be good to add extra space. It shouldn't need much extra space during runtime but I guess it's mainly the previous docker containers, cache etc.
